kubevirt/cloud-image-builder

environment.aws

Created a base CentOS AMI that does not include the marketplace
product code. This will allow us to make our AMIs public.

Update base CentOS AMI to one that we can make public

---

ec2-test-centos-cleanup.yml

The playbook should be executed after ec2-test-centos.yml to
terminate the ec2 instance that may have been created during
the test.

Playbook to terminate test instance

---

aws-ami-publish.yml

Uses packer build manifest from test step.
The source and published image are made public.
Creates a file called published-aws-image-ids which contains a list
of <region>:<ami_id>.

Publish AMI to all AWS region

---

ansible.cfg
aws-build-base-ami.yml

Builds the AWS base image from CentOS marketplace image and strips
out the product code. The product code presence blocks derivative
AMIs from being made public.

Playbook to build AWS base image

---

kubevirt-ami-centos.json

They got lost during the ci pipeline merge.

Add back motd and emulation-configmap for aws

---

build.sh

Forces kubevirt-ansible to use 0.8.0-alpha.0.
This version of KubeVirt fixes compatibility issues with K8S v1.11
and issues with missing tun devices when /dev/kvm is missing.

Use KubeVirt 0.8.0-alpha.0

---

kubevirt-ami-centos.json

The instance name was not being set during image build, so it
defaulted to "Packer Builder". The name needs to be unique
in the event multiple PRs trigger multiple CI builds.

Fix AWS build instance name

---

gcp-test-centos-cleanup.yml
gcp-test-centos.yml
kubevirt-gcp-centos.json

Instance name needs to be unique for each PR and tagged release,
because multiple CI builds can run concurrently.
Image name is used as the instance name. Assumes instance name
contains PR # and build #. A PR can trigger multiple builds.

Parameterize GCP instance name

---

Jenkinsfile

GCP doesn't allow periods in image names.

Replace '.' with '-' in image names

---

aws-ami-publish.yml

Removed the wait in ec_ami_copy. Added a wait step afterwards to
check AMIs in each region has reached available status before they
are made public.
Also removed ap-northeast-3 region (Osaka) because it requires additional
registration in order to use it.

Parallelize AWS publishing

---

Jenkinsfile

This change is needed because builds with publishing step active
are timing out.

Add timeout of 120 mins to build pipeline

---

build.sh

The variable in kubevirt-ansible is on an older version, 0.8.0-alpha.1.

Update build.sh to use version 0.8.0

---

Jenkinsfile

published-aws-image-ids is a file containing the AMI ids and regions
that were published. This should be archived.

Have CI also archive published-aws-image-ids

---

build.sh
gcp-image-publish.yml

The version number was hard-coded. The version number should be
determined from what kubevirt-ansbile will install.

Determine KubeVirt version for GCP publish

---

README.md

It may not be obvious where the pages are located.

Add links to EC2 and GCP pages to help users locate the source

---

build.sh
image-files/multus-config.yml
kubevirt-ami-centos.json

Recent changes in kubevirt-ansible has broken upstream kubernetes deployments. The fixes in this patch include:
1. An update to use Ansible version 2.6, so that multus provisioning does fail on a field loop issue. (https://github.com/kubevirt/cloud-image-builder/issues/59)
2. An update to the cdi provisioning to skip a step that only should run on OpenShift. (https://github.com/kubevirt/kubevirt-ansible/issues/398)
3. An update to the multus config file so that it uses the weave-net instead of flannel. 
(https://github.com/kubevirt/kubevirt-ansible/issues/401)
2 & 3 should be removed once kubevirt-ansible is updated with the appropriate fix.
Fixes issue https://github.com/kubevirt/cloud-image-builder/issues/59

Fix kubevirt ansible and multus issues

---

image-files/first-boot-centos.sh

The CDI is removed because it will cause a conflict when users tries to 
create it when completing lab7.

Remove CDI during first boot

---

gcp-image-publish.sh.j2
gcp-image-publish.yml

Added cleanup steps to ensure instances and disks aren't reused.
Copies of images should be taken from /dev/sdb instead of /sdev/sdb1. Otherwise, they do not boot.

GCP publishing fix

---

build.sh

weavenet.stdout should be surrounded by "{{ }}". It is currently
interpreted as a string and not returning the value it represents.

Add fix for weavenet.stdout

---

gcp-test-centos-cleanup.yml
tests/test-instance-shutdown.yml
tests/tests.yml

Needed to speed up GCP instance delete. GCP deletes are timing out
because it is taking longer than 180s.

Shutdown instance after tests are complete

---

tests/cdi-lab.yml
tests/tests.yml
tests/use-kubevirt-lab.yml

We want tighter integration between the commands the users are using in 
the labs and the commands we execute in the CI tests.
Parts of the commands used in the kubernetes lab on kubevirt.io have 
been templated out into the labs_kuberentes_variables.yml file. This 
change updates the tests to read in the variables from this file and 
then use the variables to form test commands.

Update tests to use commands from kubevirt.io website

---

tests/pretest-checks.yml
tests/tests.yml

Should wait for virt-handler to be running before executing tests.

Add check for virt-handler pod and virt-api service

---

tests/pretest-checks.yml
tests/tests.yml

Should wait for virt-handler to be running and virt-api service
to be available before executing tests.

Add checks for virt-handler pod and virt-api service

---

ec2-test-centos-cleanup.yml
ec2-test-centos.yml
gcp-test-centos-cleanup.yml
gcp-test-centos.yml
read-packer-manifest-aws.yml
read-packer-manifest-gcp.yml

The images built by the CI to validate pull requests can be deleted
during the cleanup setup. They are not meant to be consumed by the
public. Currently, they are not deleted and just accumulate after the CI
run.
Fixes issue https://github.com/kubevirt/cloud-image-builder/issues/53

Clean up images built during PR validation

---

README.md
ec2-ami-cleanup.yml

KubeVirt is now installed directly from manifest. Updated release 
process to indicate version is set in build.sh.
Add a script to cleanup old AMIs from AWS.

Update release process and add AMI cleanup

---

image-files/first-boot-centos.sh

This change adds a symlink where kubectl expects the default config to exist. This symlink points to the actual location, /home/centos/admin.conf.
This change allows scripts that access the instance by SSH but do not create an interactive session (and hence a TTY) to successfully execute kubectl commands without having to specify the location of the file in the CLI arguments.

add a symlink to the admin.conf in the kube default location

---

.gitignore
shell/build.sh

This hopefully resolves #123 
the underlying issue is that the static binaries aren't included in the git repo. I know it looks weird but the binaries are static and don't seem to change often enough for the online labs to break. Housing them in the main git repo ensure availability rather than depending upon some sort of approach in the pipeline execution where it programmatically determines that latest binary. Downloading it programmatically would always catch the latest code but runs the risk of the code breaking somehow since it depends upon things like URL's that we don't control remaining the same. This way it's all housed in a single repo that we do control.

Updating gitignore and adding binaries
