kubevirt/cloud-image-builder

- aws-build-and-test.yml
A subsequent job/playbook will need to be created
to make the tested image public and deploy it to
other regions.
> Playbook that combines build and test for AWS

- kubevirt-ami-centos.json
- kubevirt-gcp-centos.json
Manifest includes ami_id and region which are required artifacts
for test and later distribution.
> Generate Packer build manifest

- README.md
- build.sh
- environment.gcp
also properly untaint the master node to run kubevirt pods
> Ignore crd validations to run on latest k8s

- tests/emulation-configmap.yaml
The file has been moved to image-files.
> Remove emulation-configmap.yaml from tests

- kubevirt-ami-centos.json
- kubevirt-gcp-centos.json
These tools may be used when the user walks through the labs.
> Add git and wget to image

- README.md
- kubevirt-ami-centos.json
- kubevirt-gcp-centos.json
Fixed capitalization of KubeVirt.
> Update Readme with link to CI and info about releases

- build.sh
The fix has merged into kubevirt-ansible,
https://github.com/kubevirt/kubevirt-ansible/pull/402
> Remove multus patch

- test-lab2.yml
- tests.yml
Tests for http://kubevirt.io/labs/kubernetes/lab2
> Add tests for lab2

- build.sh
Use release-0.8. Changes from release-0.9 are breaking our build.
> Set kubevirt-ansible to use specific version

- build.sh
- image-files/kubevirt.yml
- image-files/provision.yml
Recent changes in kubevirt-ansible has broken Kubevirt installs on 
Kubernetes clusters.
These changes should be reverted once patches have merged to 
kubevirt-ansible.
> Fix kubevirt install issues

- build.sh
Fix has been merged to kubevirt-ansible: 
https://github.com/kubevirt/kubevirt-ansible/pull/457
> Remove temporary CDI fix

- tests/pretest-checks.yml
Otherwise validation fails with connection refused.
> Wait for virt-api port 443 to be open

- build.sh
- image-files/first-boot-centos.sh
Reuses pretest-checks.yml from tests.
> Validate KubeVirt environment after install

- aws-ami-publish.yml
- build.sh
- environment.aws
- tests/cdi-lab.yml
Other projects are using us-east-1. So let's move to a region that is unused.
> Move to AWS us-west-1 region

- build.sh
- image-files/after-install-checks.yml
- image-files/first-boot-centos.sh
- image-files/motd.yml
- kubevirt-ami-centos.json
- kubevirt-gcp-centos.json
- tests/cdi-lab.yml
- tests/pretest-checks.yml
- tests/tests.yml
- tests/use-kubevirt-lab.yml
Website switched from using variables in yaml file to scriplets.
> Update tests to use scriplets

- image-files/first-boot-centos.sh
The line removed was an error.  It would have tried to create a symlink where the file had already been copied.
> remove duplicate symlink

- OWNERS
* List reviewers and approvers
> feat: add owners file

- tests/cdi-lab.yml
This update should resolve the testing issues that stem from the ordering present in the CDI controller's yaml file.
I ran a test build (including testing) and it completed successfully:
https://jenkins-kubevirt.apps.ci.centos.org/job/dev/job/jodavis/job/cloud-image-builder/job/release-0.16.1/39/
> Resolve testing issue

- OWNERS
Add the OWNERS file to the release-0.16.1 branch
> Add OWNERS to the 0.16.1 branch

- LICENSE
**What this PR does / why we need it**:
Following the same way-of-work as Kubevirt repo, we will use the same LICENSE file on this one
**Does this PR fix any issue?**:
This PR fixes #120
> Fix: Added LICENSE file

- .gitignore
- ansible/aws-setup.yml
- ansible/gcp-setup.yml
- ansible/minikube-setup.yml
Replace local copy of binary blows in repository by download of url's matching version
> Use downloads

- shell/build.sh
- shell/deploy_kubernetes.j2
- shell/first-boot.sh
- shell/publish.sh
Use Curl as wget was failing on build.sh and adjust spacing
> Use curl and adjust spacing

- shell/first-boot.sh
> Fix URL in motd

- ansible/minikube-setup.yml
> define kv version

- Jenkinsfile
Disable minikube and notify on slack
> Disable minikube and notify on slack

- Jenkinsfile
Change subject of notifications in slack
> Change subject of notifications

- Jenkinsfile
- ansible/aws-publish.yml
- shell/build.sh
- shell/publish.sh
Update jenkins jobs to check artifact creation
> Update jenkins jobs to check artifact creation

- shell/build.sh
- shell/publish.sh
> Restore log creation path

- shell/first-boot.sh
Patches issue with Firewalld  until https://github.com/kubevirt/kubevirt-ansible/pull/625 lands
> Add Patch to allow deploying kubernetes

- Jenkinsfile
Reenable minikube image creation
> Reenable minikube

- README.md
- ansible/aws-publish.yml
Reduce AWS publish regions to lower task completing time
> Reduce AWS publish regions
